"""add soft delete fields to containers

Revision ID: 038c53f42db2
Revises: 6ee8049538b5
Create Date: 2026-08-01 12:56:11.783287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038c53f42db2'
down_revision: Union[str, Sequence[str], None] = '6ee8049538b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('containers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.drop_column('containers', 'deleted_at')
    op.drop_column('containers', 'is_deleted')
    # ### end Alembic commands ###
