"""add logistics models

Revision ID: 3dfdb7cdd28f
Revises: 8b04c13e704b
Create Date: 2026-07-24 12:28:20.244022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfdb7cdd28f'
down_revision: Union[str, Sequence[str], None] = '8b04c13e704b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('logistics_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_logistics_companies_id'), 'logistics_companies', ['id'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('container_number', sa.String(length=50), nullable=False),
    sa.Column('shipping_line', sa.String(length=100), nullable=False),
    sa.Column('container_type', sa.Enum('DRY', 'REEFER', 'OPEN_TOP', 'FLAT_RACK', 'TANK', name='containertype'), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'UNDER_MAINTENANCE', 'RETIRED', name='containerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['logistics_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('container_number', 'shipping_line', name='uq_container_number_shipping_line')
    )
    op.create_index(op.f('ix_containers_container_number'), 'containers', ['container_number'], unique=True)
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_index(op.f('ix_containers_shipping_line'), 'containers', ['shipping_line'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_TRIP', 'INACTIVE', name='driverstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['logistics_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('current_status', sa.Enum('PENDING', 'BOOKED', 'IN_TRANSIT', 'AT_PORT', 'CUSTOMS_HOLD', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELAYED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('current_location', sa.String(length=150), nullable=True),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['logistics_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_number'), 'shipments', ['shipment_number'], unique=True)
    op.create_table('shipment_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('BILL_OF_LADING', 'INVOICE', 'PACKING_LIST', 'CUSTOMS_DECLARATION', 'CERTIFICATE_OF_ORIGIN', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_documents_id'), 'shipment_documents', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_documents_shipment_id'), 'shipment_documents', ['shipment_id'], unique=False)
    op.create_table('shipment_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.Enum('PORT', 'WAREHOUSE', 'CUSTOMS_CHECKPOINT', 'LOGISTICS_CENTER', 'OTHER', name='locationtype'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_routes_id'), 'shipment_routes', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_routes_shipment_id'), 'shipment_routes', ['shipment_id'], unique=False)
    op.create_table('shipment_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BOOKED', 'IN_TRANSIT', 'AT_PORT', 'CUSTOMS_HOLD', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELAYED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_status_history_id'), 'shipment_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_shipment_id'), 'shipment_status_history', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_status_history_shipment_id'), table_name='shipment_status_history')
    op.drop_index(op.f('ix_shipment_status_history_id'), table_name='shipment_status_history')
    op.drop_table('shipment_status_history')
    op.drop_index(op.f('ix_shipment_routes_shipment_id'), table_name='shipment_routes')
    op.drop_index(op.f('ix_shipment_routes_id'), table_name='shipment_routes')
    op.drop_table('shipment_routes')
    op.drop_index(op.f('ix_shipment_documents_shipment_id'), table_name='shipment_documents')
    op.drop_index(op.f('ix_shipment_documents_id'), table_name='shipment_documents')
    op.drop_table('shipment_documents')
    op.drop_index(op.f('ix_shipments_shipment_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_containers_shipping_line'), table_name='containers')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_container_number'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_logistics_companies_id'), table_name='logistics_companies')
    op.drop_table('logistics_companies')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
