"""add container_size to containers

Revision ID: 40d185e4992a
Revises: a23538af2484
Create Date: 2026-08-01 14:22:22.789073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40d185e4992a'
down_revision: Union[str, Sequence[str], None] = 'a23538af2484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'container_size',
               existing_type=postgresql.ENUM('TWENTY_FT', 'FORTY_FT', 'FORTY_FT_HC', 'FORTY_FIVE_FT_HC', name='containersize'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'container_size',
               existing_type=postgresql.ENUM('TWENTY_FT', 'FORTY_FT', 'FORTY_FT_HC', 'FORTY_FIVE_FT_HC', name='containersize'),
               server_default=sa.text("'TWENTY_FT'::containersize"),
               existing_nullable=False)
    # ### end Alembic commands ###
